# Generated by Django 4.2 on 2025-07-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('life', '生活'), ('hobby', '趣味'), ('comic', '漫画'), ('other', 'その他')], max_length=100)),
            ],
        ),
    ]
