# Generated by Django 4.2 on 2025-07-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_review_thumbnail_shelf_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(choices=[('ビジネス', 'ビジネス'), ('生活', '生活'), ('趣味', '趣味'), ('漫画', '漫画'), ('その他', 'その他')], max_length=100),
        ),
    ]
